version: '3'
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    enviroment:
      - NODE_ENV=development
    command: npm run dev    